### ISSUE TITLE
CSS methodology

### ISSUE THREAD

**Issue by oxyc** [generoi/genero-design-system#8]
Which CSS methodology should we use?

I guess my own vote would go for BEM even if i'm not always happy with it. And we should probably use the same convention for CSS variable names.

Example https://github.com/generoi/genero-design-system/pull/7/commits/5f895e06b2a31bd2f01c2ea12b8b02503b4aafe6

**Comment by oxyc** [comment]
And how do we deal with things like responsive variations? Sounds a bit difficult to build in a clean way without having sass loops/maps/etc.

**Comment by oxyc** [comment]
Doh just realized responsive variations is really easy with css variables.

```scss
:root {
  --responsive-padding: 1rem;
}

@media (min-width: 600px) {                             
  :root {
    --responsive-padding: 2rem;
  }
}

.foo {
  padding: var(--responsive-padding);
}
```
